main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    #path('busca', views.BuscaView.as_view(), name="busca"),
    path('perfil/<int:pk>', views.PerfilView.as_view(), name="perfil"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('cadastro-usuario', views.CadastroView.as_view(), name="cadastro-usuario"),
    path('buscar-pessoas', views.BuscarPessoas, name='buscar-pessoas'),

    #path('interesse/<int:pk>', views.DemonstrarInteresseView, name="interesse"),
    #path('interessados/<int:pk>', views.interessados, name='interessados'),
    
    path('demonstrar-interesse/<int:pk>', views.DemonstrarInteresse, name='demonstrar-interesse'),    
    path('meus-interesses/<int:pk>', views.MeusInteresses, name='meus-interesses'),
    path('solicitacoes-interesse/<int:pk>', views.SolicitacoesInteresse, name='solicitacoes-interesse'),
    path('aceitar-interesse/<int:pk>', views.AceitarInteresse, name='aceitar'),
    path('recusar-interesse/<int:pk>', views.RecusarInteresse, name='recusar'),


]

moramigo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.contrib.auth.models import User
from django.db import models
import datetime
class Pessoa(models.Model):
    
    GENERO_CHOICES = (
        ('M', "Masculino"),
        ('F', "Feminino"),
        ('O', "Outra classificação")
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=255)
    senha = models.CharField(max_length=30)
    # foto = models.ImageField()
    descricao = models.CharField(max_length=255, blank=True)
    nome = models.CharField(max_length=255)
    data_nascimento = models.DateTimeField("Data de nascimento")
    genero = models.CharField(max_length=1, choices=GENERO_CHOICES)
    ocupacao = models.CharField(max_length=40)
    contato = models.CharField(max_length=10)
    interessados = models.ManyToManyField("Pessoa", blank=True, symmetrical=False, related_name='interesses')
 
    def __str__(self):
        return self.nome

    def idade(self):
        return datetime.datetime.today().year - self.data_nascimento.year

class Restricoes(models.Model):    
    pessoa = models.OneToOneField(Pessoa, on_delete=models.CASCADE)    
    
    PREFERENCIA_GENERO_CHOICES = (
        ('M', "Quero morar apenas com homens."),
        ('F', "Quero morar apenas com mulheres."),
        ('I', "Não tenho preferência do gênero com quem quero dividir.")
    )
    ANIMAIS_CHOICES = (
        ('S', "Moraria numa casa com animais."),
        ('D', "Moraria dependendo do animal."),
        ('N', "Não moraria com animais."),
        ('I', "Tanto faz para mim morar ou não com animais.")
    )
    VISITAS_CHOICES = (
        ('S', "Posso morar tranquilamente com pessoas que recebem visitas."),
        ('N', "Não quero mesmo morar com pessoas que recebem visitas."),
        ('I', "Tanto faz para mim morar ou não com pessoas que recebem visitas."),        
    )
    BEBIDAS_CHOICES = (
        ('S', "Posso morar tranquilamente com pessoas que bebem."),
        ('N', "Não quero mesmo morar com pessoas que bebem."),
        ('I', "Tanto faz pra mim morar ou não com pessoas que bebem."),
    )
    FUMANTES_CHOICES = (
        ('S', "Posso morar tranquilamente com pessoas que fumam."),
        ('N', "Não quero mesmo morar com pessoas que fumam."),
        ('I', "Tanto faz pra mim morar ou não com pessoas que fumam."),        
    )
    valor_contribuicao = models.DecimalField(max_digits=8, decimal_places=2)    
    genero_companheiro = models.CharField(max_length=1, choices=PREFERENCIA_GENERO_CHOICES)
    animais = models.CharField(max_length=1, choices=ANIMAIS_CHOICES)
    visitas = models.CharField(max_length=1, choices=VISITAS_CHOICES)
    bebidas = models.CharField(max_length=1, choices=BEBIDAS_CHOICES)
    fumantes = models.CharField(max_length=1, choices=FUMANTES_CHOICES)
    localidades = models.ManyToManyField("Bairro", related_name='restricoes')

    def __str__(self):
        return "Restrição de {}".format(self.pessoa)

class Bairro(models.Model):
    nome = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.nome

main/views.py
from django.shortcuts import render, reverse, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views import generic
from  .models import Pessoa, Restricoes
from .filters import RestricoesFilter

class HomeView(generic.ListView):
    model = Pessoa
    template_name = "main/home.html"

def BuscarPessoas(request):
    restricoes = Restricoes.objects.all()
    restricoes_filter = RestricoesFilter(request.GET, queryset=restricoes)
    return render(request, 'main/buscar-pessoas.html', {'restricoes':restricoes_filter})

class BuscaView(generic.ListView):
    model = Pessoa
    template_name = 'main/busca.html'

class PerfilView(generic.DetailView):
    model = Pessoa
    template_name = 'main/perfil.html'

def login_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('main:home'))
    else:
        if request.method == 'POST':
            usuario = request.POST.get('username')
            senha = request.POST.get('senha')
            tentativa_login = authenticate(request, username=usuario, password=senha)

            if tentativa_login is not None:
                login(request, tentativa_login)
                return redirect(reverse('main:home'))
            else:
                # messages.error(request, 'Usuário não encontrado: tente novamente')
                messages.error(request, 'O nome de usuário inserido ou senha está Incorreto. Verifique  e tente novamente.')


        return render(request, 'main/login.html', {})

def logout_view(request):
    logout(request)
    return redirect(reverse('main:home'))

class CadastroView(generic.TemplateView):
    model = Pessoa
    template_name = 'main/cadastro-usuario.html'

@login_required(login_url='main:login')
def DemonstrarInteresse(request, pk):
    pessoa_que_vou_demonstrar_interesse = Pessoa.objects.get(pk=pk)
    if (pessoa_que_vou_demonstrar_interesse.id != request.user.pessoa.id):
        request.user.pessoa.interessados.add(pessoa_que_vou_demonstrar_interesse)
    else:
        print("Não posso demonstrar interesse no meu próprio perfil")
        return redirect(reverse('main:perfil', args=(request.user.pessoa.id,)))
    return render(request, 'main/interesse.html', {})

@login_required(login_url='main:login')
def MeusInteresses(request, pk):
    meus_interesses = request.user.pessoa.interessados.all()
    solicitacoes_aceitas = []
    solicitacoes_pedentes = []
    for solicitacao in meus_interesses:
        if request.user.pessoa in solicitacao.interessados.all(): #Se o usuário estiver nos interessados da outra pessoa
            solicitacoes_aceitas.append(solicitacao)
        else:
            solicitacoes_pedentes.append(solicitacao)

    return render(request, 'main/interesse.html', {'solicitacoes_aceitas':solicitacoes_aceitas, 'solicitacoes_pedentes':solicitacoes_pedentes})

@login_required(login_url='main:login')
def SolicitacoesInteresse(request, pk):
    meus_interesses = request.user.pessoa.interessados.all() #Quem já aceitei
    solicitacoes_interesse = request.user.pessoa.interesses.all() #Quem já aceitei e quem não aceitei
    nao_aceito = [p for p in solicitacoes_interesse if p not in meus_interesses] #Filtrar as solicitações de interesse
    print(nao_aceito)
    return render(request, 'main/meus-interesses.html', {'solicitacoes':nao_aceito})

@login_required(login_url='main:login')
def AceitarInteresse(request, pk):
    pessoa_aceita = Pessoa.objects.get(pk=pk)
    request.user.pessoa.interessados.add(pessoa_aceita)
    #request.user.pessoa.interesses.delete(pk=request.user.pessoa.id)
    return render(request, 'main/meus-interesses.html', {})

@login_required(login_url='main:login')
def RecusarInteresse(request, pk):
    pessoa_recusada = Pessoa.objects.get(pk=pk) #Recuperando id, pessoa recusada
    request.user.pessoa.interesses.remove(pessoa_recusada) #Removendo das solicitações de interesse a pessoa recusada
    return redirect(reverse('main:solicitacoes-interesse', args=(request.user.pessoa.id,)))

main/templates/main/busca.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Busca | MorAmigo</title>
</head>
<body>

    <a href="{% url 'main:home' %}"> Home </a> |
    <h1> Lista de pessoas </h1>
    {% for pessoa in pessoa_list %}
        
        <hr>
        <h2> {{pessoa.nome}} </h2>
        <p>Bairros inteteressados:</p>
        <ul>
            {%for bairro in pessoa.restricoes.localidades.all%}
                <li>{{bairro}}</li>        
            {%endfor%}
        </ul>
        <p>Posso contribuir: R$ {{pessoa.restricoes.valor_contribuicao}}</p>
        <a href="{% url 'main:perfil' pessoa.id %}">Ver perfil</a>
            
    {%endfor%}

</body>
</html>

main/templates/main/demonstrou-interesse.html
<html>
    <head>

    </head>

    <body>
        <h1>Você demonstrou interesse em {{pessoa.nome}}</h1>        
        <a href="{% url 'main:meus-interesses' user.pessoa.id %}">Meus interesses</a>

    </body>
</html>

main/templates/main/home.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width,user-scalable=0" />

	<link rel="stylesheet" type="text/css" href="{% static 'main/styles/home.css'%}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'main/styles/partials/minha-conta.css'%}"/>
	 <script src="{% static 'main/javascript/minha-conta.js'%}"></script>

	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
		integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
	<script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
		integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
		crossorigin="anonymous"></script>

	<style>
		#banner {
			background-image:url("{% static '/main/images/banner.svg'%}");
		}
	</style>

	<script type="text/javascript">
		window.onload = function () {
			document.querySelector(".menuMobile").addEventListener("click", function () {
				if (document.querySelector(".menu nav ul").style.display == 'flex') {
					document.querySelector(".menu nav ul").style.display = 'none';
				} else {
					document.querySelector(".menu nav ul").style.display = 'flex';
				}
			});
		};
	</script>



	<title>MorAmigo | MorAmigo</title>

</head>

<body>

	<header>
		<div class="container">
			<div class="logo">
					<a href="{% url 'main:home'%}"><img src="{% static 'main/images/logo.svg'%}" /></a>

			</div>
			<div class="menu">
				<nav>
					<div class="menuMobile">
						<div class="mm_line"></div>
						<div class="mm_line"></div>
						<div class="mm_line"></div>
					</div>
					<ul>

						<!-- <li class="active"><a href="">HOME</a></li> -->

						<li><a href="{% url 'main:buscar-pessoas' %}"><i class="fas fa-search"></i> Buscar Pessoas</a></li>


						{% if user.is_authenticated %}
						<li><a href="{% url 'main:meus-interesses' user.pessoa.id %}"><i class="fas fa-user"></i> Meus Interesses</a></li>


									<div class="dropdown">
										<button onclick="myFunction()" class="dropbtn"><i class="fas fa-user"></i> Minha Conta <i class="fa fa-caret-down"></i></button>

										<div id="myDropdown" class="dropdown-content">
										  <a href=""><i class="fas fa-user"></i> Olá, {{user}}</a>

										  <a href="{%url 'main:perfil' request.user.pessoa.id %}"><i class="fas fa-user"></i> Meu perfil</a>
										  <a href="{% url 'main:meus-interesses' user.pessoa.id %}"><i class="fas fa-user"></i> Meus Interesses</a>

										  <a href="{% url 'main:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
										</div>
									  </div>


								{% else %}

									<li><a href="{% url 'main:login' %}"><i class="fas fa-sign-in-alt"></i> Entrar</a></li>
									<li><a href="{% url 'main:cadastro-usuario' %}"><i class="far fa-file-alt"></i> Cadastre-se</a></li>
						{% endif %}
						{% if user.is_authenticated %}
						<!-- <p>Olá, {{user}}</p>
						 -->
						{% endif %}


					</ul>
				</nav>
			</div>
		</div>
	</header>

	<section id="banner">
		<div class="banner_headline">
			<h2>Encontrar uma galera bacana <br>

				para compartilhar moradia <br>

				não precisa ser uma tarefa difícil.</h2>
		</div>
	</section>

	<section id="geral">
		<div class="container column">
			<div class="banner_options">
				{% for pessoa in pessoa_list %}
					<div class="banner1">
						<div class="foto-perfil">
							<img src="{% static '/main/images/pessoa1.svg'%}" alt="usuario">
							<h3> {{pessoa.nome}}, {{pessoa.idade}}  anos</h3>

						</div>



						<div class="conteudo">
							<p>{{pessoa.descricao}}</p>
						 </div>

							{%for bairro in pessoa.restricoes.localidades.all%}

							<div class="bairro">
								<p><i class="fas fa-home-lg-alt"></i> Bairro: {{bairro}}</p>
							 </div>

            				{%endfor%}

						<a href="{%url 'main:perfil' pessoa.id %}">Ver Perfil</a>
					</div>
				{%endfor%}

			</div>
		</div>


	</section>

	<footer>
		<div class="container flexColumn">

			<div class="footer_copy">
				Copyright - Todos os direitos reservados
			</div>

		</div>
	</footer>

</body>
</html>

main/templates/main/meus-interesses.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width,user-scalable=0" />

    <link rel="stylesheet" type="text/css" href="{% static 'main/styles/partials/solicitacaoInteresse.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/styles/partials/minha-conta.css'%}" />
    <script src="{% static 'main/javascript/minha-conta.js'%}"></script>

	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
		integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
	<script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
		integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
        crossorigin="anonymous"></script>

	<script type="text/javascript">
		window.onload = function () {
			document.querySelector(".menuMobile").addEventListener("click", function () {
				if (document.querySelector(".menu nav ul").style.display == 'flex') {
					document.querySelector(".menu nav ul").style.display = 'none';
				} else {
					document.querySelector(".menu nav ul").style.display = 'flex';
				}
			});
		};
	</script>


<title>Meus interesses | MorAmigo</title>

</head>

<body>

	<header>
		<div class="container">
			<div class="logo">
				<a href="{% url 'main:home'%}"><img src="{% static 'main/images/logo.svg'%}" /></a>
			</div>
			<div class="menu">
				<nav>
					<div class="menuMobile">
						<div class="mm_line"></div>
						<div class="mm_line"></div>
						<div class="mm_line"></div>
					</div>
					<ul>

						<li><a href="{% url 'main:home' %}"><i class="fas fa-home-lg"></i> Home</a></li>
						<li><a href="{% url 'main:buscar-pessoas' %}"><i class="fas fa-search"></i> Buscar Pessoas</a></li>



						{% if user.is_authenticated %}

                        <div class="dropdown">
                            <button onclick="myFunction()" class="dropbtn"><i class="fas fa-user"></i> Minha Conta <i class="fa fa-caret-down"></i></button>
                            <div id="myDropdown" class="dropdown-content">
                              <a href=""><i class="fas fa-user"></i> Olá, {{user}}</a>
							  <a href=""><i class="fas fa-user"></i> Meu perfil</a>
							  <a href="{% url 'main:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>

                            </div>
                          </div>


                    {% else %}

                        <li><a href="{% url 'main:login' %}"><i class="fas fa-sign-in-alt"></i> Entrar</a></li>
                     {% endif %}

					</ul>
				</nav>
			</div>
		</div>
    </header>



<div class="page-topo">

	<button class="btn-solicitacao"><a href="{% url 'main:solicitacoes-interesse' user.pessoa.id %}">Solicitações de interesse</a></button>
    <button class="btn-meusInteresse"><a href="{% url 'main:meus-interesses' user.pessoa.id %}">Meus interesses</a></button>
</div>

	<section id="geral">
		<div class="container column">
			<div class="banner_options">

				{% for solicitacao in solicitacoes %}
					<div class="banner1">
						<div class="foto-perfil">
							<img src="{% static '/main/images/pessoa1.svg'%}" alt="usuario">
							<h3>{{solicitacao.nome}}, {{solicitacao.idade}} anos</h3>

						</div>
						<div class="ver-perfil">
							<a href="{%url 'main:perfil' solicitacao.id %}"><i class="fas fa-user"></i> Ver perfil</a>
						</div>

						<div class="conteudo">
							<p>{{solicitacao.descricao}}</p>
						</div>

						{%for bairro in solicitacao.restricoes.localidades.all%}

						<div class="bairro">
							<p><i class="fas fa-home-lg-alt"></i> Bairro: {{bairro}}</p>
						 </div>


						{%endfor%}


						<button class="btn-aceitar">
							<a href="{% url 'main:aceitar' solicitacao.id %}"><i class="far fa-check-circle"></i> Aceitar</a>
						</button>

						<button class="btn-recusar">
							<a href="{% url 'main:recusar' solicitacao.id %}"><i class="far fa-times-circle"></i> Recusar</a>
						</button>

					</div>
				{% endfor %}

			</div>
		</div>

	</section>

	<footer>
		<div class="container flexColumn">

			<div class="footer_copy">
				Copyright - Todos os direitos reservados
			</div>

		</div>
	</footer>
</body>
</html>

main/templates/main/perfil.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width,user-scalable=0" />

    <link rel="stylesheet" type="text/css" href="{% static 'main/styles/perfil.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/styles/partials/minha-conta.css'%}" />
    <script src="{% static 'main/javascript/minha-conta.js'%}"></script>

	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
		integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
	<script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
		integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
        crossorigin="anonymous"></script>




	<script type="text/javascript">
		window.onload = function () {
			document.querySelector(".menuMobile").addEventListener("click", function () {
				if (document.querySelector(".menu nav ul").style.display == 'flex') {
					document.querySelector(".menu nav ul").style.display = 'none';
				} else {
					document.querySelector(".menu nav ul").style.display = 'flex';
				}
			});
		};
	</script>


<title>Perfil | MorAmigo</title>

</head>

<body>

	<header>
		<div class="container">
			<div class="logo">
				<a href="{% url 'main:home'%}"><img src="{% static 'main/images/logo.svg'%}" /></a>
			</div>
			<div class="menu">
				<nav>
					<div class="menuMobile">
						<div class="mm_line"></div>
						<div class="mm_line"></div>
						<div class="mm_line"></div>
					</div>
					<ul>
						<!-- <li class="active"><a href="">HOME</a></li> -->
						<li><a href="{% url 'main:home' %}"><i class="fas fa-home-lg"></i> Home</a></li>
						<li><a href="{% url 'main:buscar-pessoas' %}"><i class="fas fa-search"></i> Buscar Pessoas</a></li>
						<!-- <li><a href="{%url 'main:perfil' pessoa.id %}"><i class="fas fa-user"></i> Meu perfil</a></li> -->


						{% if user.is_authenticated %}

                        <div class="dropdown">
                            <button onclick="myFunction()" class="dropbtn"><i class="fas fa-user"></i> Minha Conta <i class="fa fa-caret-down"></i></button>
                            <div id="myDropdown" class="dropdown-content">
                              <a href=""><i class="fas fa-user"></i> Olá, {{user}}</a>

                              <a href="{%url 'main:perfil' user.pessoa.id %}"><i class="fas fa-user"></i> Meu perfil</a>
                              <a href="{% url 'main:meus-interesses' user.pessoa.id %}"><i class="fas fa-user"></i> Meus Interesses</a>

                              <a href="{% url 'main:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                            </div>
                          </div>


                    {% else %}

                        <li><a href="{% url 'main:login' %}"><i class="fas fa-sign-in-alt"></i> Entrar</a></li>
                     {% endif %}

					</ul>
				</nav>
			</div>
		</div>
    </header>

    <!-- <hr> -->

<div class="page-perfil">

    <div class="page-tabela">
                <div class="topo" >
                    <img src="{% static '/main/images/pessoa1.svg'%}" alt="usuario">
                    <p>{{pessoa.nome}}</p>

                    {% if user.is_authenticated %}

                        {% if user.pessoa.id == pessoa.pk %}
                            <button class="butto"><a href="{% url 'main:meus-interesses' user.pessoa.id %}">Meus interesses</a></button>
                        {% else %}
                            {% if user.pessoa in pessoa.interessados.all %}
                                <button class="butto" name="interesse"><a href="{% url 'main:meus-interesses' user.pessoa.id %}">Você já demonstrou interesse</a></button>

                            {% else %}
                            <button class="butto" name="interesse"><a href="{% url 'main:demonstrar-interesse' pessoa.id%}">Demonstrar interesse</a></button>
                            {% endif %}
                        {% endif %}
                    {% endif %}

                    {% if user.is_authenticated == False %}
                     <button class="butto"><a href="{% url 'main:login' %}">Faça login para Demonstrar interesse</a></button>
                    {% endif %}

                </div>



            <div class="descricao">
                <p>{{pessoa.descricao}}</p>
            </div>


            <table class="tabela1">
                <thead class="bg-warning">

                    <tr>
                        <th ><i class="far fa-id-card"></i> Dados Pessoais</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><i class="fas fa-restroom"></i> Gênero: {{pessoa.get_genero_display}}</td>
                    </tr>
                    <tr>
                        <td><i class="fas fa-tools"></i> Ocupação: {{pessoa.ocupacao}}</td>
                    </tr>
                </tbody>
            </table>

            <table class="tabela2">
                <thead class="bg-warning">
                    <tr>
                        <th><i class="far fa-smile"></i> Interesses</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><i class="fas fa-map-marker-alt"></i> Bairro: {%for bairro in pessoa.restricoes.localidades.all%} {{bairro}}/{%endfor%} </td>
                    </tr>
                    <tr>
                        <td><i class="fas fa-hand-holding-usd"></i>  Posso contribuir: {{pessoa.restricoes.valor_contribuicao}}</td>
                    </tr>
                    <tr>
                        <td><i class="fas fa-restroom"> Gênero de um possível colega de casa:</i> {{pessoa.restricoes.get_genero_companheiro_display}}</td>
                    </tr>
                </tbody>
            </table>

            <table class="tabela3">
                <thead class="bg-warning">
                    <tr>
                        <th><i class="fas fa-exclamation-circle"></i> Restrições</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><i class="fas fa-paw"></i> Animais: {{pessoa.restricoes.get_animais_display}}</td>
                    </tr>
                    <tr>
                        <td><i class="fas fa-home-lg-alt"></i> Visitas: {{pessoa.restricoes.get_visitas_display}}</td>
                    </tr>
                    <tr>
                        <td><i class="fas fa-wine-bottle"></i> Bebidas: {{pessoa.restricoes.get_bebidas_display}}</td>
                    </tr>
                    <tr>
                        <td><i class="fas fa-smoking"></i>  Fumantes:{{pessoa.restricoes.get_fumantes_display}}</td>
                    </tr>
                </tbody>
            </table>

            <table class="tebela4">
                <thead class="bg-warning">
                    <tr>
                        <th><i class="far fa-address-book"></i> Contatos</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>A pessoa precisa aceitar sua solicitação de interesse para
                        que os contatos sejam exibidos! </td>
                </tbody>
            </table>
        </div>

</div>


	<footer>
		<div class="container flexColumn">

			<div class="footer_copy">
				Coyright - Todos os direitos reservados
			</div>

		</div>
	</footer>
</body>
</html>